---
- name: Merge new data to conf files, not commit yet
  hosts: all
  become: true

  vars:
    local_data_list:
      - name: svr01.hoge.example.com
        addresses:
          - 10.1.1.1
          - 10.1.1.2
          - 10.1.1.3
      - name: svr04.hoge.example.com
        state: absent
    container_name: "unbound_{{ ansible_env.JOB_ID }}"

  pre_tasks:
    - name: Start unbound container
      command: >-
        podman run -d --rm
        --name {{ container_name }}
        {{ unbound_image }}
      delegate_to: localhost
      run_once: true

  tasks:
    - name: Looping for each managing domain
      include_tasks: conf_repo_merge_domain.yml
      loop: "{{ unbound_managing_domains }}"
      loop_control:
        loop_var: target_domain
