---
proj1:
  hosts:
    unbound1.example.com:
      unbound_listen_addresses:
        - 192.168.122.209
    unbound2.example.com:
      unbound_listen_addresses:
        - 192.168.122.145
  vars:
    unbound_managing_domains:
      - hoge.example.com
      - foo.example.com

proj2:
  hosts:
    rhel8-sandbox.example.com:
      unbound_listen_addresses:
        - 192.168.122.226
  vars:
    unbound_managing_domains:
      - bar.example.com

unbound:
  children:
    proj1:
    proj2:
  vars:
    unbound_allowed_networks:
      - 192.168.122.0/24
    unbound_default_nameservers:
      - 192.168.122.1

all:
  hosts:
    bastion:
      ansible_host: tower.example.com
  vars:
    ansible_user: root
    ansible_connection: ssh
    unbound_data_git:
      repo: git@gitlab.example.com:test-user/unbound-conf-repo.git
      version: master
    unbound_container:
      image: localhost/my-unbound:ci
      port: 1053
