---
- name: Update Unbound local-data
  hosts: all
  become: true
  gather_facts: false
  roles:
    - role: unbound_container
      tags:
        - update
    - role: unbound_data
      tags:
        - update
