---
- name: Update Unbound local-data
  hosts: unbound
  become: true
  gather_facts: false

  pre_tasks:
    - block:
      - include_vars: # noqa 502
          roles/unbound_data/defaults/main.yml
      - include_tasks:
          roles/unbound_data/tasks/validation.yml
      delegate_to: bastion
      run_once: true
      tags:
        - validation

  tasks:
    - include_role:
        name: unbound_data
        apply:
          delegate_to: bastion
          run_once: true
      vars:
        test_container_name: "unbound_{{ tower_job_id | default('0') }}"
        unbound_data_dir: "/tmp/unbound-data_{{ tower_job_id | default('0') }}"
      tags:
        - update
