---
- name: Update Unbound local-data
  hosts: all
  become: true
  gather_facts: false

  vars:
    # Test data
    dns_entries:
      - name: svr01.hoge.example.com
        address: 10.1.1.1
      - name: svr01.hoge.example.com
        address: 10.1.1.2
      - name: svr02.hoge.example.com
        address: 10.1.2.1
      - name: svr01.foo.example.com
        address: 10.2.1.1
      - name: svr99.foo.example.com
        state: absent

  pre_tasks:
    - block:
      - include_vars: # noqa 502
          roles/unbound_data/defaults/main.yml
      - include_tasks:
          roles/unbound_data/tasks/validation.yml
      delegate_to: bastion
      run_once: true
      tags:
        - validation

  tasks:
    - include_role:
        name: unbound_data
        apply:
          delegate_to: bastion
          run_once: true
          tags:
            - update
      vars:
        test_container_name: "unbound_{{ tower_job_id | default('0') }}"
        unbound_data_dir: "/tmp/unbound-data_{{ tower_job_id | default('0') }}"
      tags:
        - update
