---
- name: Update Unbound local-data
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: unbound_data
        apply:
          delegate_to: bastion
          run_once: true
      tags:
        - update
