---
- name: Update Unbound local-data
  hosts: all
  become: true
  gather_facts: false

  pre_tasks:
    - block:
      - name: Include variables first
        include_vars:
          roles/unbound_data/defaults/main.yml
      - name: Validate dns_entries and unbound_managing_domains
        include_tasks:
          roles/unbound_data/tasks/validate.yml
      delegate_to: bastion
      run_once: true
      tags:
        - validate

  roles:
    - role: unbound_data
      vars:
        git_repo: "{{ unbound_data_push_url }}"
        git_version: "{{ unbound_data_version }}"
        git_dest: "/tmp/unbound_data_{{ tower_job_id | default('0') }}"
        git_enable_commit_handler: true
        git_enable_push_handler: true
        git_enable_remove_handler: true
        podman_image: "{{ unbound_container_image }}"
        podman_tag: "{{ unbound_container_tag }}"
        podman_container_name: "unbound_{{ tower_job_id | default('0') }}"
        podman_enable_stop_handler: true
        podman_enable_remove_handler: true
      delegate_to: bastion
      run_once: true
      tags:
        - update
