---
- name: Install Unbound
  dnf:
    name:
      - unbound
      - bind-utils
      - git
    state: present

- name: Delete unnecessary default files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/unbound/conf.d/example.com.conf
    - /etc/unbound/keys.d/example.com.key
    - /etc/unbound/local.d/block-example.com.conf

- name: Basic server setting for Unbound
  template:
    src: my-server.conf.j2
    dest: /etc/unbound/conf.d/my-server.conf
    backup: true
  notify:
    - Restart Unbound server

- name: Copy Unbound data files of this server
  copy:
    src: "{{ git_dest }}/{{ item }}.conf"
    dest: /etc/unbound/local.d/{{ item }}.conf
    remote_src: true
    backup: true
  loop: "{{ unbound_managing_domains }}"
  notify:
    - Restart Unbound server

- name: Validate the config files
  command: /usr/sbin/unbound-checkconf
  register: res_unbound_checkconf
  changed_when: false

- name: Open ports for DNS service
  firewalld:
    service: dns
    permanent: true
    immediate: true
    state: enabled

- name: Make sure Unbound started
  service:
    name: unbound
    state: started
    enabled: true
