---
- name: Start once to generate initial files like unbound_control.key # noqa 301
  command: >-
    podman run -d --name {{ ubc_temp_container_name }}
    {{ ubc_image_name }}
  notify:
    - Cleanup Unbound temp container

- name: Wait until the container has started
  command: >-
    podman exec {{ ubc_temp_container_name }} dig @localhost localhost
  changed_when: false
  register: res_podman_exec
  until: res_podman_exec.rc == 0
  # timeout is 60 sec
  retries: 12
  delay: 5

- name: Stop the container # noqa 301
  command: >-
    podman stop {{ ubc_temp_container_name }}

- name: Commit the container # noqa 301
  command: >-
    podman commit {{ ubc_temp_container_name }}
    {{ ubc_image_name }}
