---
- name: Start Unbound Podman container for test # noqa 301
  # BUG: "-P" option doesn't expose udp port.
  # BUG WORKAROUND: Use "-p" explicitly.
  command: >-
    podman run --rm -d -p 53/tcp -p 53/udp
    {{ ubc_image_name }}
  register: res_podman_run
  notify:
    - Cleanup Unbound Podman container

- name: Memoize the container ID
  set_fact:
    podman_container_id: "{{ res_podman_run.stdout }}"

- name: Determin a port randomly assined
  # BUG: udp port is not opened, only tcp port.
  shell: >-
    set -o pipefail &&
    podman port {{ podman_container_id }} |
    awk -F ':' '/udp/ {print $2}'
  register: res_podman_port
  changed_when: false

- name: Memoize the container port
  set_fact:
    podman_container_port: "{{ res_podman_port.stdout }}"

- name: Wait for the container started
  # BUG WORKAROUND: Don't use the opened port. Test inside container.
  command: >-
    podman exec {{ podman_container_id }} dig @localhost localhost
  changed_when: false
  register: res_podman_exec
  until: res_podman_exec.rc == 0
  # timeout is 300 sec
  retries: 100
  delay: 3
