---
galaxy_info:
  author: Osamu Nagano
  description: To do Git oeprations of pull, commit, and push.
  license: BSD-3-Clause or MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags: []
dependencies: []
