---
galaxy_info:

  author: Osamu Nagano

  description: A role to install Unbound

  license: BSD

  min_ansible_version: 2.8

  platforms:
  - name: EL
    versions:
    - 8

  galaxy_tags: []

dependencies: []
