---
- name: Podman stop {{ podman_container_name }}
  shell: >-
    podman stop {{ podman_container_name }} &&
    podman wait {{ podman_container_name }}
  when: podman_enable_stop_handler

- name: Podman remove {{ podman_container_name }}
  command: >-
    podman rm {{ podman_container_name }}
  when: podman_enable_remove_handler
